// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXHhWa3XErIWcQ9ydi-2RCibmaVa7gQnQ',
    appId: '1:321428581589:web:d75233e5a20135555d465c',
    messagingSenderId: '321428581589',
    projectId: 'doancnpm-33225',
    authDomain: 'doancnpm-33225.firebaseapp.com',
    databaseURL: 'https://doancnpm-33225-default-rtdb.firebaseio.com',
    storageBucket: 'doancnpm-33225.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4V9gP5MBSi9UVslblvKOqK1x4z0RiO4E',
    appId: '1:321428581589:android:da19f0c21c5ad3355d465c',
    messagingSenderId: '321428581589',
    projectId: 'doancnpm-33225',
    databaseURL: 'https://doancnpm-33225-default-rtdb.firebaseio.com',
    storageBucket: 'doancnpm-33225.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEhX4y5Y8sinkd721rFxgiPq0uWPYuNBY',
    appId: '1:321428581589:ios:7cb3fb62452f8e405d465c',
    messagingSenderId: '321428581589',
    projectId: 'doancnpm-33225',
    databaseURL: 'https://doancnpm-33225-default-rtdb.firebaseio.com',
    storageBucket: 'doancnpm-33225.appspot.com',
    iosBundleId: 'com.example.bao24h',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEhX4y5Y8sinkd721rFxgiPq0uWPYuNBY',
    appId: '1:321428581589:ios:ef27db6257c3bb995d465c',
    messagingSenderId: '321428581589',
    projectId: 'doancnpm-33225',
    databaseURL: 'https://doancnpm-33225-default-rtdb.firebaseio.com',
    storageBucket: 'doancnpm-33225.appspot.com',
    iosBundleId: 'com.example.bao24h.RunnerTests',
  );
}
